AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  burger-api-sam

  Sample SAM Template for burger-api-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Architectures:
        - x86_64
    CodeUri: api/
    Environment:
        Variables:
          DATABASE_URL: postgresql://postgres:docker@172.20.0.2:5432/sam-challenge?schema=public
    Runtime: nodejs20.x
    Timeout: 3
  Api:
    OpenApiVersion: '3.0.0'

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: 15.5
      MasterUsername: postgres
      MasterUserPassword: docker
      DBInstanceIdentifier: sam-challenge
      PubliclyAccessible: true
      DBName: postgres

  CreateIngredientFunction:
    Type: AWS::Serverless::Function
    DependsOn: DBInstance
    Properties:
      Handler: app.createIngredientHandler
      Events:
        CreateIngredient:
          Type: Api
          Properties:
            Path: /ingredients
            Method: post

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - app.ts
        Loader:
        - .prisma=file
        - .so.node=file
        AssetNames: '[name]'

  GetAllIngredientsFunction:
    Type: AWS::Serverless::Function
    DependsOn: DBInstance
    Properties:
      Handler: app.getAllIngredientsHandler
      Events:
        GetAllIngredients:
          Type: Api
          Properties:
            Path: /ingredients
            Method: get

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - app.ts
        Loader:
        - .prisma=file
        - .so.node=file
        AssetNames: '[name]'

  UpdateIngredientFunction:
    Type: AWS::Serverless::Function
    DependsOn: DBInstance
    Properties:
      Handler: app.updateIngredientHandler
      Events:
        UpdateIngredient:
          Type: Api
          Properties:
            Path: /ingredients/{id}
            Method: patch

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - app.ts
        Loader:
        - .prisma=file
        - .so.node=file
        AssetNames: '[name]'

  DeleteIngredientFunction:
    Type: AWS::Serverless::Function
    DependsOn: DBInstance
    Properties:
      Handler: app.deleteIngredientHandler
      Events:
        DeleteIngredient:
          Type: Api
          Properties:
            Path: /ingredients/{id}
            Method: delete

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - app.ts
        Loader:
        - .prisma=file
        - .so.node=file
        AssetNames: '[name]'

  CreateSnackFunction:
    Type: AWS::Serverless::Function
    DependsOn: DBInstance
    Properties:
      Handler: app.createSnackHandler
      Events:
        CreateSnack:
          Type: Api
          Properties:
            Path: /snacks
            Method: post

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - app.ts
        Loader:
        - .prisma=file
        - .so.node=file
        AssetNames: '[name]'

  DeleteSnackFunction:
    Type: AWS::Serverless::Function
    DependsOn: DBInstance
    Properties:
      Handler: app.deleteSnackHandler
      Events:
        DeleteSnack:
          Type: Api
          Properties:
            Path: /snacks/{id}
            Method: delete

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - app.ts
        Loader:
        - .prisma=file
        - .so.node=file
        AssetNames: '[name]'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateIngredientFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn